
export const indianCities = [
  "Abohar", "Abu Road", "Addanki", "Adilabad", "Adityapur", "Adoni", "Adoor", "Agar Malwa", 
  "Agartala", "Agra", "Ahmedabad", "Ahmednagar", "Ahwa", "Aizawl", "Ajitgarh", "Ajmer", 
  "Akashiganga", "Akbarpur", "Akhnoor", "Akluj", "Akola", "Alagappapuram", "Alamcode", 
  "Alandi", "Alappuzha", "Alibag", "Aligarh", "Alipore", "Alipurduar", "Alirajpur", 
  "Allagadda", "Allahabad", "Almora", "Aluva", "Alwar", "Amalapuram", "Amb", "Ambajogai", 
  "Ambala", "Ambala Cantonment", "Ambasamudram", "Ambedkar Nagar", "Ambegaon", "Ambernath", 
  "Ambikapur", "Amethi", "Amloh", "Amod", "Amravati", "Amreli", "Amritsar", "Amroha", 
  "Anakapalle", "Anand", "Anandapur", "Anantapur", "Anantnag", "Angul", "Ankleshwar", 
  "Arakkonam", "Arambag", "Araria", "Arcot", "Ariyalur", "Armoor", "Arni", "Arrah", 
  "Arsikere", "Aruppukottai", "Arwal", "Asansol", "Ashoknagar", "Athani", "Attingal", 
  "Aurangabad", "Avadi", "Azamgarh", "Baddi", "Badlapur", "Bagalkot", "Bageshwar", "Baghpat", 
  "Bahadurgarh", "Bahraich", "Baidyabati", "Balaghat", "Balangir", "Balasore", "Ballabhgarh", 
  "Ballia", "Balrampur", "Balurghat", "Banda", "Bangalore", "Bangarapet", "Bankura", "Banswara", 
  "Bapatla", "Baramati", "Baramulla", "Baran", "Bardhaman", "Bareilly", "Bargarh", "Baripada", 
  "Barmer", "Barnala", "Barpeta", "Barrackpore", "Basirhat", "Basti", "Batala", "Bathinda", 
  "Beawar", "Begusarai", "Belgaum", "Bellary", "Bettiah", "Betul", "Bhadohi", "Bhadrachalam", 
  "Bhadrak", "Bhadravathi", "Bhagalpur", "Bhandara", "Bharatpur", "Bharuch", "Bhatapara", 
  "Bhatinda", "Bhavnagar", "Bhawanipatna", "Bhilai", "Bhilwara", "Bhimavaram", "Bhind", 
  "Bhiwadi", "Bhiwani", "Bhopal", "Bhubaneswar", "Bhuj", "Bhusawal", "Bidar", "Bidhannagar", 
  "Bihar Sharif", "Bikaner", "Bilaspur", "Birbhum", "Bishnupur", "Bokaro", "Bolangir", 
  "Bongaigaon", "Botad", "Budaun", "Bulandshahr", "Buldhana", "Bundi", "Burhanpur", "Buxar", 
  "Chaibasa", "Chakradharpur", "Chamba", "Chamoli", "Champawat", "Chamrajnagar", "Chandauli", 
  "Chandausi", "Chandigarh", "Chandrapur", "Chapra", "Chennai", "Chhapra", "Chhatarpur", 
  "Chhindwara", "Chikballapur", "Chikmagalur", "Chiplun", "Chitradurga", "Chitrakoot", 
  "Chittoor", "Chittorgarh", "Churachandpur", "Churu", "Coimbatore", "Cooch Behar", "Coonoor", 
  "Cuddalore", "Cuttack", "Dahod", "Daltonganj", "Daman", "Damoh", "Darbhanga", "Darjeeling", 
  "Datia", "Dausa", "Davangere", "Dehradun", "Dehri", "Delhi", "Deoghar", "Deoria", "Dewas", 
  "Dhalai", "Dhamtari", "Dhanbad", "Dhar", "Dharmapuri", "Dharwad", "Dhemaji", "Dhenkanal", 
  "Dholpur", "Dhubri", "Dhule", "Dibrugarh", "Dimapur", "Dindigul", "Diu", "Doda", "Dumka", 
  "Dungarpur", "Durg", "Durgapur", "East Champaran", "East Godavari", "East Khasi Hills", 
  "East Singhbhum", "Ernakulam", "Erode", "Etah", "Etawah", "Faizabad", "Faridabad", "Faridkot", 
  "Farrukhabad", "Fatehabad", "Fatehgarh Sahib", "Fatehpur", "Fazilka", "Firozabad", "Firozpur", 
  "Gadag", "Gadchiroli", "Gajapati", "Gandhinagar", "Ganganagar", "Gangapur", "Ganjam", "Garhwa", 
  "Gariaband", "Gautam Buddha Nagar", "Gaya", "Ghaziabad", "Ghazipur", "Gir Somnath", "Giridih", 
  "Goalpara", "Godda", "Godhra", "Gokak", "Golaghat", "Gonda", "Gondia", "Gopalganj", "Gorakhpur", 
  "Gulbarga", "Gumla", "Guna", "Guntur", "Gurdaspur", "Gurgaon", "Guwahati", "Gwalior", "Hailakandi", 
  "Hamirpur", "Hanumangarh", "Hapur", "Harda", "Hardoi", "Haridwar", "Hassan", "Hathras", "Haveri", 
  "Hazaribagh", "Hindaun", "Hindupur", "Hingoli", "Hisar", "Hooghly", "Hoshangabad", "Hoshiarpur", 
  "Hospet", "Hosur", "Howrah", "Hubli", "Hyderabad", "Idukki", "Imphal", "Indore", "Itanagar", 
  "Jabalpur", "Jagdalpur", "Jaipur", "Jaisalmer", "Jalandhar", "Jalaun", "Jalgaon", "Jalna", 
  "Jalpaiguri", "Jammu", "Jamnagar", "Jamui", "Janjgir-Champa", "Jashpur", "Jaunpur", "Jehanabad", 
  "Jhabua", "Jhajjar", "Jhalawar", "Jhansi", "Jharsuguda", "Jhunjhunu", "Jind", "Jodhpur", "Jorhat", 
  "Junagadh", "Kabirdham", "Kadapa", "Kaithal", "Kakinada", "Kalahandi", "Kalaburagi", "Kamrup", 
  "Kanchipuram", "Kandhamal", "Kangra", "Kanker", "Kannauj", "Kannur", "Kanpur", "Kanpur Dehat", 
  "Kanyakumari", "Kapurthala", "Karaikal", "Karauli", "Karbi Anglong", "Kargil", "Karimganj", 
  "Karimnagar", "Karnal", "Karur", "Kasaragod", "Kasganj", "Kathua", "Katihar", "Katni", "Kaushambi", 
  "Kendrapara", "Kendujhar", "Khammam", "Khandwa", "Khargone", "Kheda", "Khordha", "Khunti", "Kinnaur", 
  "Kishanganj", "Kishtwar", "Kodagu", "Koderma", "Kohima", "Kokrajhar", "Kolar", "Kolhapur", "Kolkata", 
  "Kollam", "Koppal", "Koraput", "Korba", "Koriya", "Kota", "Kottayam", "Kozhikode", "Krishna", 
  "Krishnagiri", "Kulgam", "Kullu", "Kupwara", "Kurnool", "Kurukshetra", "Kurung Kumey", "Kushinagar", 
  "Kutch", "Lahaul and Spiti", "Lakhimpur", "Lakhisarai", "Lalitpur", "Latur", "Leh", "Lohardaga", 
  "Lohit", "Longleng", "Lower Dibang Valley", "Lower Subansiri", "Lucknow", "Ludhiana", "Lunglei", 
  "Madhepura", "Madhubani", "Madurai", "Maharajganj", "Mahasamund", "Mahbubnagar", "Mahe", "Mahendragarh", 
  "Mahisagar", "Mahoba", "Mainpuri", "Malappuram", "Maldah", "Malkangiri", "Mamit", "Mandi", "Mandla", 
  "Mandsaur", "Mandya", "Mansa", "Marigaon", "Mathura", "Mau", "Mayurbhanj", "Medak", "Meerut", "Mehsana", 
  "Mewat", "Mirzapur", "Moga", "Mohali", "Mokokchung", "Mon", "Moradabad", "Morena", "Mumbai", "Mungeli", 
  "Munger", "Murshidabad", "Muzaffarnagar", "Muzaffarpur", "Mysore", "Nabarangpur", "Nadia", "Nagaon", 
  "Nagapattinam", "Nagaur", "Nainital", "Nalanda", "Nalbari", "Nalgonda", "Namakkal", "Nanded", "Nandurbar", 
  "Narayanpur", "Narmada", "Narsinghpur", "Nashik", "Navsari", "Nawada", "Nayagarh", "Neemuch", "Nizamabad", 
  "North 24 Parganas", "North Goa", "North Sikkim", "Nuapada", "Osmanabad", "Pakur", "Palakkad", "Palamu", 
  "Palghar", "Pali", "Palwal", "Panchkula", "Panchmahal", "Panipat", "Panna", "Papum Pare", "Parbhani", 
  "Patan", "Pathanamthitta", "Pathankot", "Patiala", "Patna", "Pauri Garhwal", "Perambalur", "Peren", 
  "Phek", "Pilibhit", "Pithoragarh", "Pollachi", "Pondicherry", "Poonch", "Porbandar", "Prakasam", "Pratapgarh", 
  "Pudukkottai", "Pulwama", "Pune", "Purba Medinipur", "Puri", "Purnia", "Purulia", "Raebareli", "Raichur", 
  "Raigad", "Raigarh", "Raipur", "Raisen", "Rajauri", "Rajgarh", "Rajkot", "Rajnandgaon", "Rajsamand", 
  "Ramanathapuram", "Ramban", "Ramgarh", "Rampur", "Ranchi", "Ranga Reddy", "Ratnagiri", "Rayagada", 
  "Reasi", "Rewa", "Rewari", "Ri Bhoi", "Rohtak", "Rohtas", "Rudraprayag", "Rupnagar", "Sabarkantha", 
  "Sagar", "Saharanpur", "Saharsa", "Sahibganj", "Salem", "Samastipur", "Samba", "Sambalpur", "Sangli", 
  "Sangrur", "Sant Kabir Nagar", "Sant Ravidas Nagar", "Saraikela Kharsawan", "Saran", "Satara", "Satna", 
  "Sawai Madhopur", "Sehore", "Seoni", "Seraikela Kharsawan", "Serchhip", "Shahdol", "Shahjahanpur", 
  "Shajapur", "Shamli", "Sheikhpura", "Sheohar", "Sheopur", "Shimla", "Shimoga", "Shivpuri", "Shopian", 
  "Shravasti", "Siddharth Nagar", "Sikar", "Simdega", "Sindhudurg", "Singrauli", "Sirmaur", "Sirohi", 
  "Sirsa", "Sitamarhi", "Sitapur", "Sivaganga", "Siwan", "Solan", "Solapur", "Sonbhadra", "Sonipat", 
  "Sonitpur", "South 24 Parganas", "South Goa", "South Sikkim", "South Tripura", "Sri Muktsar Sahib", 
  "Srikakulam", "Srinagar", "Sukma", "Sultanpur", "Sundargarh", "Supaul", "Surajpur", "Surat", "Surendranagar", 
  "Surguja", "Tamenglong", "Tarn Taran", "Tawang", "Tehri Garhwal", "Thane", "Thanjavur", "Theni", "Thiruvananthapuram", "Thoothukudi",
  "Thoubal", "Thrissur", "Tikamgarh", "Tinsukia", "Tirap", "Tiruchirappalli", "Tirunelveli", "Tirupur", 
  "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Tonk", "Tuensang", "Tumkur", "Udaipur", "Udalguri", 
  "Udham Singh Nagar", "Udhampur", "Udumalipet", "Udupi", "Ujjain", "Ukhrul", "Umaria", "Una", "Unnao", "Upper Siang", 
  "Upper Subansiri", "Uttar Dinajpur", "Uttara Kannada", "Uttarkashi", "Vadodara", "Vaishali", "Valsad", 
  "Varanasi", "Vellore", "Vidisha", "Vijayapura", "Vijayanagara", "Vijayawada", "Vikarabad", "Viluppuram", 
  "Virudhunagar", "Visakhapatnam", "Vizianagaram", "Warangal", "Wardha", "Washim", "West Champaran", 
  "West Godavari", "West Kameng", "West Khasi Hills", "West Siang", "West Singhbhum", "West Tripura", 
  "Wokha", "Yadgir", "Yamunanagar", "Yavatmal", "Zunheboto"
];
