
export const mockBikeListings = [
  {
    id: 1,
    name: "yamaha r15 v3",
    image: "https://kujjqfvicrazqitxkdwh.supabase.co/storage/v1/object/public/seller-uploads/temp/bike/right/r15_v3_right.jpg",
    year: 2020,
    kmDriven: 20000,
    fuelType: "Petrol",
    transmission: "Manual",
    owner: "First Owner",
    bikeType: "Solo White Pillion",
    color: "Mat Gray Metallic 3",
    seats: 2,
    price: 195000,
    location: "Mumbai",
    seller: "Certified Dealer",
    badges: ["Certified", "Well Maintained"],
    features: ["ABS", "Digital Console", "Alloy Wheels"]
  },
  {
    id: 2,
    name: "Honda CB Shine",
    image: "https://images.unsplash.com/photo-1597595366138-905d75933f36?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80",
    year: 2020,
    kmDriven: 8500,
    fuelType: "Petrol",
    transmission: "Manual",
    owner: "First Owner",
    bikeType: "Commuter",
    color: "Blue",
    seats: 2,
    price: 75000,
    location: "Delhi",
    seller: "Individual",
    badges: ["Good Condition"],
    features: ["LED Headlights", "Alloy Wheels"]
  },
  {
    id: 3,
    name: "Yamaha R15 V3",
    image: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80",
    year: 2022,
    kmDriven: 3000,
    fuelType: "Petrol",
    transmission: "Manual",
    owner: "First Owner",
    bikeType: "Sports",
    color: "Red",
    seats: 2,
    price: 175000,
    location: "Bangalore",
    seller: "Certified Dealer",
    badges: ["Certified", "Top Model"],
    features: ["ABS", "Digital Console", "LED Headlights", "Alloy Wheels"]
  },
  {
    id: 4,
    name: "TVS Jupiter",
    image: "https://images.unsplash.com/photo-1571325654970-60aa4a1e4fac?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80",
    year: 2021,
    kmDriven: 4500,
    fuelType: "Petrol",
    transmission: "Automatic",
    owner: "First Owner",
    bikeType: "Scooty",
    color: "Grey",
    seats: 2,
    price: 65000,
    location: "Chennai",
    seller: "Individual",
    badges: ["Well Maintained"],
    features: ["Alloy Wheels", "Keyless Start"]
  },
  {
    id: 5,
    name: "Bajaj Pulsar NS200",
    image: "https://images.unsplash.com/photo-1614846384571-1e31c018a232?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80",
    year: 2020,
    kmDriven: 12000,
    fuelType: "Petrol",
    transmission: "Manual",
    owner: "Second Owner",
    bikeType: "Sports",
    color: "Black",
    seats: 2,
    price: 105000,
    location: "Pune",
    seller: "Certified Dealer",
    badges: ["Certified"],
    features: ["ABS", "Digital Console", "Alloy Wheels"]
  },
  {
    id: 6,
    name: "Hero Electric Optima",
    image: "https://images.unsplash.com/photo-1612051855818-daecf51a14ed?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80",
    year: 2022,
    kmDriven: 1500,
    fuelType: "Electric",
    transmission: "Automatic",
    owner: "First Owner",
    bikeType: "Electric",
    color: "White",
    seats: 2,
    price: 85000,
    location: "Hyderabad",
    seller: "Individual",
    badges: ["Eco-friendly"],
    features: ["Digital Console", "LED Headlights"]
  }
];
